music/urls.py
from django.urls import path

from music import views

urlpatterns = [
    path("", views.index, name="index"),

    path('signup/', views.signup, name="signup"),

    path("new/genre/", views.GenreCreate.as_view(), name="create-genre"),

    path("new/label/", views.CreateLabel.as_view(), name="create-label"),

    path("all/", views.MusicList.as_view(), name="musics"),

    path("new/", views.create_music, name="create-music"),

    path("update/<int:pk>/", views.UpdateMusic.as_view(), name="update-music"),

    path("open/<slug:slug>/", views.MusicDetail.as_view(), name="music"),

]

musicpey/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),

    path("music/", include('music.urls')),
    path("", RedirectView.as_view(url="music/", permanent=True)),

]
urlpatterns += static(settings.STATIC_URL, document_type=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
import string
import random


class Genre(models.Model):
    title = models.CharField(max_length=500, blank=True, null=True)
    slug = models.SlugField(max_length=100, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.title

    def clean(self):

        genres = ["Rock", "Pop music", "Hip hop music", "Jazz", "Folk music", "Blues", "Popular music", "Heavy metal", "Country music", "Classical music", "Rhythm and blues", "Electronic dance music", "Electronic music", "Soul music", "Dance music", "Disco", "Techno", "Trance music", "Indie rock", "Alternative rock", "Instrumental", "Singing", "Dubstep", "Ambient music", "Pop rock",
 "Afrobeat", "African hip hop", "African heavy metal", "Benga", "Boomba", "Bongo Flava", "Fuji", "Highlife", "Hiplife",
        ]

        errors = {}
        title = self.title
        if title not in genres:
            errors['title'] = _(f"Must be one of genre from {genres}")
        if errors:
            raise ValidationError(errors)


def new_music_image_save(instance, filename):
    return 'images/{0}/{1}'.format(instance.title, filename)


def new_music_save(instance, filename):
    return 'music/{0}/{1}'.format(instance.title, filename)


class Album(models.Model):
    music = models.ForeignKey("Music", on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=500, null=True, blank=True)
    slug = models.SlugField(max_length=100, unique=True)
    band = models.ForeignKey("Band", on_delete=models.SET_NULL, null=True)
    label = models.ForeignKey("Label", on_delete=models.SET_NULL, null=True)
    asin = models.CharField(max_length=200, null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to=new_music_image_save, null=True, blank=True)
    genre = models.ManyToManyField(Genre, blank=True)

    def __str__(self):
        return self.title


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class Music(models.Model):
    title = models.CharField(max_length=300, null=True)
    audio_file = models.FileField(upload_to=new_music_save, blank=True, null=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + "-" + str(self.title))
        super(Music, self).save(*args, **kwargs)


class Band(models.Model):
    band = models.CharField(max_length=300, null=True, blank=True)
    music = models.ManyToManyField("Music", blank=True)

    def __str__(self):
        return self.band


class Label(models.Model):
    label = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.label

music/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from music.models import Music


class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=200, required=False, help_text="First Name")
    last_name = forms.CharField(max_length=200, required=False, help_text="Last Name")
    email = forms.CharField(max_length=200, required=False, help_text="Enter email")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class MusicForm(forms.ModelForm):
    class Meta:
        model = Music
        fields = ("title", "audio_file")

    def clean(self):
        cleaned_data = super(MusicForm, self).clean()
        title = cleaned_data.get("title")
        audio_file = cleaned_data.get("audio_file")

        errors = {}
        if len(str(title)) < 7:
            raise ValidationError(_("Length of song name must be greater than 5 Characters"))

        if audio_file is None:
            raise ValidationError(_("You must also upload a music file."))

        if errors:
            raise ValidationError(errors)
        return cleaned_data

music/views.py
from django.contrib import messages
from django.db import transaction
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from music.forms import SignupForm, MusicForm
from music.models import Genre, Label, Music
from django.urls import reverse_lazy, reverse


def index(request):
    return render(request, "index.html")


class GenreCreate(generic.CreateView):
    model = Genre
    fields = ("title",)
    success_url = '/'


class CreateLabel(generic.CreateView):
    model = Label
    fields = ("label",)
    success_url = "/"


class MusicList(generic.ListView):
    model = Music


@transaction.atomic
@login_required
def create_music(request):
    if request.POST:
        form = MusicForm(request.POST, request.FILES)
    else:
        form = MusicForm()

    if form.is_valid():
        form_obj = form.save()
        messages.success(request, "Your music was successfully added. Happy MusicPey!")
        return redirect("music", form_obj.slug)

    params = {
        'form': form,
    }
    return render(request, "music/new-music.html", params)


class UpdateMusic(generic.UpdateView):
    model = Music
    fields = ("title", "audio_file")
    success_url = reverse_lazy("musics")


def update_music(request, pk):
    music_object = get_object_or_404(Music, id=pk)
    form = MusicForm(request.POST or None, request.FILES or None, instance=music_object)
    params = {
        'form': form,
    }
    return render(request, "music/update-music.html", params)


class MusicDetail(generic.DetailView):
    model = Music


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password1)
            if user is not None:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect('index')
            else:
                return HttpResponse("Invalid username & password")

    else:
        form = SignupForm()
    return render(request, 'registration/signup.html', {'form': form})

music/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
    <style>
        body {
            font-family: "Microsoft YaHei" !important;
            font: "Microsoft YaHei" !important;
            font-size: 18pt !important;
        }

        #footer {
            position: fixed;
            bottom: 0px;
            left: 0px;
            right: 0px;
            background-color: paleturquoise;
        }

        a {
            text-decoration: navajowhite;
        }
        {% block style %}{% endblock %}</style>
</head>
<body>
<nav class="navbar navbar-expand-lg border navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">MusicPey</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>

            </ul>

            <ul class="navbar-nav me-auto mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Settings
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if not user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'signup' %}">Signup</a></li>
                        {% else %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="container">
    <div class="row mt-4">
        <div class="col-lg-3  col-md-12 mt-5 col-sm-12">
            <ul class="list-group list-group-flush" {% block visibility %}{% endblock %}>
                <li class="list-group-item text-center"><a href="{% url 'musics' %}"> Browse Music</a></li>
                <li class="list-group-item text-center"><a href="{% url 'create-music' %}"> Add Music</a></li>
                <li class="list-group-item text-center"><a href="#"> Browse Genre</a></li>
                <li class="list-group-item text-center"><a href="{% url 'create-genre' %}"> Add New  Genre</a></li>
                <li class="list-group-item text-center"><a href="{% url 'create-label' %}"> Add New Label</a></li>
            </ul>
        </div>

        <div class="col-lg-8 col-lg-8 mt-5 md-12 col-md-12 col-sm-12">
            {% for message in messages %}
                <div class="mb-5 alert alert-{{ message.tags }} alert-dismissible fade p-1 show" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="p-2 btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}

            {% block body %}{% endblock %}
        </div>
    </div>
</div>

<br><br><br>
<footer id="footer">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-dark" href="https://moviesoppo14.herokuapp.com">moviesoppo.com</a>
    </div>
    <!-- Copyright -->
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

music/templates/index.html
{% extends 'base.html' %}

{% block title %}MusicPey{% endblock %}

{% block body %}
<div class="row text-center mt-3">
<a href="{% url 'musics' %}"><h1>Start here</h1></a>
</div>
{% endblock %}

music/templates/music/genre_form.html
{% extends 'base.html' %}

{% block title %}Login - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

    #id_username, #id_password{
    padding: 12px;
    margin-bottom: 22px;
    font-size: 20px;
    border: 1px solid lightgrey;
    background-color:white;
    margin-top: 1%;
    }

{% endblock %}
{% block body %}

    <h2 class="text-center vLargeTextField">Add a new Genre type in MusicPey</h2>
    <hr>
    <div class="mt-4"></div>
    <label for="inputEmail4" style="color: red" class="form-label">{{ form.errors.title }}</label>

    <form method="post" action="#" class="row g-3">
        {% csrf_token %}
        <div class="col-md-4">
            <label for="inputEmail4" class="form-label">Genre</label>
            <input type="text" class="form-control" name="{{ form.title.name }}" id="inputEmail4">
        </div>

        <div class="col-12">
            <button type="submit" class="btn btn-primary btn-sm">Save</button>
        </div>

    </form>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

music/templates/music/label_form.html
{% extends 'base.html' %}

{% block title %}Login - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

    #id_username, #id_password{
    padding: 12px;
    margin-bottom: 22px;
    font-size: 20px;
    border: 1px solid lightgrey;
    background-color:white;
    margin-top: 1%;
    }

{% endblock %}
{% block body %}

    <h2 class="text-center vLargeTextField">Add a new Label in MusicPey</h2>
    <hr>
    <div class="mt-4"></div>
    <label for="inputEmail4" style="color: red" class="form-label">{{ form.errors.title }}</label>

    <form method="post" action="#" class="row g-3">
        {% csrf_token %}
        <div class="col-md-4">
            <label for="inputEmail4" class="form-label">Label</label>
            <input type="text" class="form-control" name="{{ form.title.name }}" id="inputEmail4">
        </div>

        <div class="col-12">
            <button type="submit" class="btn btn-primary btn-sm">Save</button>
        </div>

    </form>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

music/templates/music/music_detail.html
{% extends 'base.html' %}

{% block title %}{{ music.title }} {% endblock %}

{% block style %}
    .centered {
    position: absolute;
    top: 78%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: black;
    width:100%;
    color: white;

    }

{% endblock %}

{% block body %}
    <div class="row mt-3">

        <div class="col-sm-12 p-0">
            <div class="card">
                <div class="card-body p-0">
                    <div class="col-sm-12 pt-0">
                        <div class="card">
                            {% if music.image %}
                                <img class="border card-img-tp" src="{{ music.image.url }}"
                                     style="width: 100%; height: 450px; object-fit: cover">
                            {% else %}

                                <img class="border card-img-tp"
                                     src="https://cdn.pixabay.com/photo/2021/01/15/17/01/green-5919790__480.jpg"
                                     style="width: 100%; height: 450px; object-fit: cover">
                            {% endif %}

                            <div class="card-body p-2 text-center centered">
                                {% if music.audio_file %}
                                <audio controls>
                                    <source src="horse.ogg" type="audio/ogg">
                                    <source src="{{ music.audio_file.url }}" type="audio/ogg">

                                    Your browser does not support the audio element.
                                </audio>
                                {% endif %}
                                <h2>{{ music.title }}</h2>
                            </div>

                        </div>
                    </div>

{#                    <hr>#}
{##}
                    <div class="card-body">
                        <a href="{% url 'update-music' music.id %}">Update music</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

music/templates/music/music_form.html
{% extends 'base.html' %}

{% block title %}Login - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

    #id_username, #id_password{
    padding: 12px;
    margin-bottom: 22px;
    font-size: 20px;
    border: 1px solid lightgrey;
    background-color:white;
    margin-top: 1%;
    }

{% endblock %}
{% block body %}

    <h2 class="text-center vLargeTextField">Update this music</h2>
    <hr>
    <div class="mt-4"></div>

    <form method="post" enctype="multipart/form-data" action="" class="row g-3">
        {% csrf_token %}
        <div class="col-md-12">
            <p>Update your music</p>
            {{ form.as_p }}
        </div>

        <div class="col-12">
            <button type="submit" class="btn btn-primary btn-sm">Save</button>
        </div>

    </form>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

music/templates/music/music_list.html
{% extends 'base.html' %}

{% block style %}
    .centered {
    position: absolute;
    top: 78%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: black;
    width:100%;
    color: white;
    heighdt:90px;
    }

{% endblock %}

{% block title %}From app All object_lists{% endblock %}

{% block body %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Music</li>
            <li class="breadcrumb-item active" aria-current="page">All</li>
        </ol>
    </nav>
    <div class="row text-center mt-3">
        {% if object_list %}
            <div class="row text-center mt-3">

                <h1 style="color: orangered">From app Browse object_list</h1>
                {% for music in object_list %}
                    <div class="col-sm-4 p-1 pt-4">
                        <div class="card">
                        {{ music.album_set.all.0 }}
                            {% if music.album_set.all %}
                                <img class="border card-img-tp" src="{{ music.album_set.all.0.image.url }}"
                                     style="width: 100%; height: 300px; object-fit: cover">
                            {% else %}

                                <img class="border card-img-tp"
                                     src="https://cdn.pixabay.com/photo/2021/01/15/17/01/green-5919790__480.jpg"
                                     style="width: 100%; height: 300px; object-fit: cover">
                            {% endif %}f

                            <div class="card-body centered">
                                <a href="{% url 'music' music.slug  %}" style="color: orangered" class=" card-title">{{ music.title }}</a>
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h4>No Music added.</h4>
        {% endif %}
    </div>
{% endblock %}

music/templates/music/musics.html
{% extends 'base.html' %}

{% block style %}
    .centered {
    position: absolute;
    top: 78%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: black;
    width:100%;
    color: white;
    heighdt:90px;
    }

{% endblock %}

{% block title %}All musics{% endblock %}

{% block body %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Music</li>
            <li class="breadcrumb-item active" aria-current="page">All</li>
        </ol>
    </nav>
    <div class="row text-center mt-3">
        {% if musics %}
            <div class="row text-center mt-3">

                <h1 style="color: orangered">Browse Music</h1>
                {% for music in musics %}
                    <div class="col-sm-4 p-1 pt-4">
                        <div class="card">
                        {{ music.album_set.all.0 }}
                            {% if music.album_set.all %}
                                <img class="border card-img-tp" src="{{ music.album_set.all.0.image.url }}"
                                     style="width: 100%; height: 300px; object-fit: cover">
                            {% else %}

                                <img class="border card-img-tp"
                                     src="https://cdn.pixabay.com/photo/2021/01/15/17/01/green-5919790__480.jpg"
                                     style="width: 100%; height: 300px; object-fit: cover">
                            {% endif %}

                            <div class="card-body centered">
                                <a href="{% url 'music' music.slug  %}" style="color: orangered" class=" card-title">{{ music.title }}</a>
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h4>No musics added.</h4>
        {% endif %}
    </div>
{% endblock %}

music/templates/music/new-music.html
{% extends 'base.html' %}

{% block title %}Login - TimeBlog{% endblock %}

{% block style %}
    input{
    border:1px solid green;
    padding:1%;
    padding-left:12px;
    font-size:17px
    }
    .errorlist{
    color:red;
    }

    #id_username, #id_password{
    padding: 12px;
    margin-bottom: 22px;
    font-size: 20px;
    border: 1px solid lightgrey;
    background-color:white;
    margin-top: 1%;
    }

{% endblock %}
{% block body %}

    <h2 class="text-center vLargeTextField">Add a new Label in MusicPey</h2>
    <hr>
    <div class="mt-4"></div>

    <form method="post" enctype="multipart/form-data" action="" class="row g-3">
        {% csrf_token %}
        <div class="col-md-12">
            <h1>{{ form.is_valid }}</h1>
            {{ form.as_p }}
        </div>

        <div class="col-12">
            <button type="submit" class="btn btn-primary btn-sm">Save</button>
        </div>

    </form>
    <br>
    <br>
    <br>
    <br>
{% endblock %}